language: java
sudo: false

addons:
  sonarcloud:
    organization: "jensgerdes-github"
    token:
      secure: "U299FqcJAMNfblrZF8R/ivqRk7KNdSOdcyWI4h5dgOLlQHj+HHrF2GJB2fOVeaB53snOkCycM/ZQgqTLlS1PU2NUca3TroNXj6jpNK1Erb/TXqFMKK+rmsN+hcxudDYGnQFIVnWy4lsg72jlK3Qvktt0XyfuYjMqQbsp3zwhlxw="

jdk:
- openjdk11

install: true
script: ./travis.sh
env:
- TEST=ci
- TEST=plugin SQ_VERSION=LATEST_RELEASE[6.7] SJ_VERSION=LATEST_RELEASE[5.0]
- TEST=plugin SQ_VERSION=LATEST_RELEASE[6.7] SJ_VERSION=DEV
- TEST=plugin SQ_VERSION=LATEST_RELEASE[7.2] SJ_VERSION=DEV
- TEST=plugin SQ_VERSION=LATEST_RELEASE[7.5] SJ_VERSION=DEV
- TEST=plugin SQ_VERSION=LATEST_RELEASE[7.6] SJ_VERSION=DEV
- TEST=plugin SQ_VERSION=LATEST_RELEASE[7.7] SJ_VERSION=DEV
- TEST=plugin SQ_VERSION=DEV                 SJ_VERSION=DEV
- TEST=javadoc

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar'
  - '$HOME/jvm'
  - '$HOME/maven'

notifications:
  email:
  - jens@gerdes.digital
